import sys
import os
sys.path.insert(0, r'c:\Users\Anne\Desktop\系統')
from database.db_config import get_db_engine
from sqlalchemy import text

engine = get_db_engine()
print("🔧 嘗試修復 PostgreSQL 的 IDENTITY 設定...")

with engine.connect() as conn:
    for table in ['news', 'opinions', 'locations', 'politicians', 'region_profiles', 'election_history']:
        try:
            # 取得目前最大 id
            r = conn.execute(text(f"SELECT COALESCE(MAX(id), 0) FROM {table}"))
            max_id = r.fetchone()[0]
            
            # 嘗試把 id 欄位改成 GENERATED BY DEFAULT AS IDENTITY
            # 先刪除 default，再重建
            conn.execute(text(f"ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT"))
            conn.execute(text(f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"))
            conn.execute(text(f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), {max(max_id, 1)}, true)"))
            print(f"✅ {table}: IDENTITY 設定成功 (目前 max_id={max_id})")
        except Exception as e:
            print(f"⚠️ {table}: {e}")
            try:
                conn.rollback()
            except:
                pass
    
    try:
        conn.commit()
        print("✅ 所有更改已提交")
    except Exception as e:
        print(f"Commit error: {e}")

print("\n測試 ORM 插入...")
import datetime
from sqlalchemy.orm import sessionmaker
from database.db_setup import News

Session = sessionmaker(bind=engine)
s = Session()
test_item = News(
    source="測試ORM",
    title="ORM測試新聞",
    content="測試",
    url=f"http://test.com/orm_test_{datetime.datetime.now().timestamp()}",
    publish_time=datetime.datetime.utcnow(),
    location_id=None,
    issue_category="其他",
    party_stance="未提及"
)
s.add(test_item)
try:
    s.commit()
    print(f"✅ ORM 插入成功! 新聞ID={test_item.id}")
except Exception as e:
    print(f"❌ ORM 插入失敗: {e}")
finally:
    s.close()
